# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e2e0208df8a1bf7055671e3e2829cec5"
name = "cart-milestone-app"
handle = "milestone-cart-tier-app"
application_url = "https://facilitate-turning-recordings-saying.trycloudflare.com"
embedded = true

[webhooks]
api_version = "2026-07"

[auth]
redirect_urls = [
  "https://facilitate-turning-recordings-saying.trycloudflare.com/api/auth",
  "https://facilitate-turning-recordings-saying.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[access_scopes]
scopes = "read_products,write_orders,read_themes,write_themes"