client_id = "e2e0208df8a1bf7055671e3e2829cec5"
name = "cart-milestone-app"
handle = "milestone-cart-tier-app"
application_url = "https://cartapp-q995.onrender.com"
embedded = true

[webhooks]
api_version = "2026-07"

[auth]
redirect_urls = [
  "https://cartapp-q995.onrender.com/api/auth",
  "https://cartapp-q995.onrender.com/api/auth/callback"
]